In [1]:
import pandas as pd

movies = pd.read_csv('imdb_top_1000.csv')

In [2]:
movies.head(1)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"

In [3]:
movies.drop(['Poster_Link', 'Overview', 'Meta_score', 'No_of_Votes'], axis=1, inplace=True)

In [4]:
movies.head(10)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"
5,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,"377,845,905"
6,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,"107,928,762"
7,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,"96,898,818"
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"292,576,195"
9,Fight Club,1999,A,139 min,Drama,8.8,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,"37,030,102"

In [5]:
movies.dropna(inplace=True)

In [6]:
movies.head(25)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"
5,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,"377,845,905"
6,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,"107,928,762"
7,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,"96,898,818"
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"292,576,195"
9,Fight Club,1999,A,139 min,Drama,8.8,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,"37,030,102"
10,The Lord of the Rings: The Fellowship of the Ring,2001,U,178 min,"Action, Adventure, Drama",8.8,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,"315,544,750"
11,Forrest Gump,1994,UA,142 min,"Drama, Romance",8.8,Robert Zemeckis,Tom Hanks,Robin Wright,Gary Sinise,Sally Field,"330,252,182"
12,"Il buono, il brutto, il cattivo",1966,A,161 min,Western,8.8,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo Giuffrè,"6,100,000"
13,The Lord of the Rings: The Two Towers,2002,UA,179 min,"Action, Adventure, Drama",8.7,Peter Jackson,Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,"342,551,365"
14,The Matrix,1999,A,136 min,"Action, Sci-Fi",8.7,Lana Wachowski,Lilly Wachowski,Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,"171,479,930"
15,Goodfellas,1990,A,146 min,"Biography, Crime, Drama",8.7,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,"46,836,394"
16,Star Wars: Episode V - The Empire Strikes Back,1980,UA,124 min,"Action, Adventure, Fantasy",8.7,Irvin Kershner,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,"290,475,067"
17,One Flew Over the Cuckoo's Nest,1975,A,133 min,Drama,8.7,Milos Forman,Jack Nicholson,Louise Fletcher,Michael Berryman,Peter Brocco,"112,000,000"
19,Gisaengchung,2019,A,132 min,"Comedy, Drama, Thriller",8.6,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,"53,367,844"
21,Interstellar,2014,UA,169 min,"Adventure, Drama, Sci-Fi",8.6,Christopher Nolan,Matthew McConaughey,Anne Hathaway,Jessica Chastain,Mackenzie Foy,"188,020,017"
22,Cidade de Deus,2002,A,130 min,"Crime, Drama",8.6,Fernando Meirelles,Kátia Lund,Alexandre Rodrigues,Leandro Firmino,Matheus Nachtergaele,"7,563,397"
23,Sen to Chihiro no kamikakushi,2001,U,125 min,"Animation, Adventure, Family",8.6,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,"10,055,859"
24,Saving Private Ryan,1998,R,169 min,"Drama, War",8.6,Steven Spielberg,Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,"216,540,909"
25,The Green Mile,1999,A,189 min,"Crime, Drama, Fantasy",8.6,Frank Darabont,Tom Hanks,Michael Clarke Duncan,David Morse,Bonnie Hunt,"136,801,374"
26,La vita è bella,1997,U,116 min,"Comedy, Drama, Romance",8.6,Roberto Benigni,Roberto Benigni,Nicoletta Braschi,Giorgio Cantarini,Giustino Durano,"57,598,247"

In [7]:
movies['Genre']=movies['Genre'].str.split(',').str[0]

In [8]:
movies['Runtime']=movies['Runtime'].str.split(' ').str[0]

In [9]:
movies.head(10)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,A,142,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,1972,A,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,2008,UA,152,Action,9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,1974,A,202,Crime,9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,1957,U,96,Crime,9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"
5,The Lord of the Rings: The Return of the King,2003,U,201,Action,8.9,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,"377,845,905"
6,Pulp Fiction,1994,A,154,Crime,8.9,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,"107,928,762"
7,Schindler's List,1993,A,195,Biography,8.9,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,"96,898,818"
8,Inception,2010,UA,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"292,576,195"
9,Fight Club,1999,A,139,Drama,8.8,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,"37,030,102"

In [10]:
movies_clean = movies.drop(['Genre', 'Director', 'Star1', 'Star2', 'Star3', 'Star4'], axis=1)

In [11]:
movies_clean.head(10)

,Series_Title,Released_Year,Certificate,Runtime,IMDB_Rating,Gross
0,The Shawshank Redemption,1994,A,142,9.3,"28,341,469"
1,The Godfather,1972,A,175,9.2,"134,966,411"
2,The Dark Knight,2008,UA,152,9.0,"534,858,444"
3,The Godfather: Part II,1974,A,202,9.0,"57,300,000"
4,12 Angry Men,1957,U,96,9.0,"4,360,000"
5,The Lord of the Rings: The Return of the King,2003,U,201,8.9,"377,845,905"
6,Pulp Fiction,1994,A,154,8.9,"107,928,762"
7,Schindler's List,1993,A,195,8.9,"96,898,818"
8,Inception,2010,UA,148,8.8,"292,576,195"
9,Fight Club,1999,A,139,8.8,"37,030,102"

In [12]:
movies_clean.to_csv('movies.csv', index=False)

In [13]:
actors = movies.drop(['Released_Year', 'Certificate', 'Runtime', 'IMDB_Rating', 'Gross', 'Director', 'Genre'], axis=1)

In [14]:
actors.head(10)

,Series_Title,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
5,The Lord of the Rings: The Return of the King,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom
6,Pulp Fiction,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis
7,Schindler's List,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall
8,Inception,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe
9,Fight Club,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier

In [15]:
actors.to_csv('actors.csv', index=False)

In [16]:
directors = movies.drop(['Genre', 'Released_Year', 'Certificate', 'Runtime', 'IMDB_Rating', 'Gross', 'Star1', 'Star2', 'Star3', 'Star4'], axis=1)

In [17]:
directors.head(10)

                                    Series_Title              Director
0                       The Shawshank Redemption        Frank Darabont
1                                  The Godfather  Francis Ford Coppola
2                                The Dark Knight     Christopher Nolan
3                         The Godfather: Part II  Francis Ford Coppola
4                                   12 Angry Men          Sidney Lumet
5  The Lord of the Rings: The Return of the King         Peter Jackson
6                                   Pulp Fiction     Quentin Tarantino
7                               Schindler's List      Steven Spielberg
8                                      Inception     Christopher Nolan
9                                     Fight Club         David Fincher

In [18]:
genre = movies.drop(['Released_Year', 'Certificate', 'Runtime', 'IMDB_Rating', 'Gross', 'Star1', 'Star2', 'Star3', 'Star4', 'Director'], axis=1)

In [19]:
genre.head(10)

                                    Series_Title      Genre
0                       The Shawshank Redemption      Drama
1                                  The Godfather      Crime
2                                The Dark Knight     Action
3                         The Godfather: Part II      Crime
4                                   12 Angry Men      Crime
5  The Lord of the Rings: The Return of the King     Action
6                                   Pulp Fiction      Crime
7                               Schindler's List  Biography
8                                      Inception     Action
9                                     Fight Club      Drama

In [20]:
genre.to_csv('genres.csv', index=False)